import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

const categories = ["مشكلة في الرحلة", "سلوك السائق", "مشكلة في الدفع", "مفقودات", "اقتراح أو ملاحظة"];
export default function ComplaintsScreen() {
  const colors = useColors();
  const [category, setCategory] = useState(categories[0]);
  const [details, setDetails] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [complaintId, setComplaintId] = useState<number | null>(null);
  const complaintMutation = trpc.complaints.create.useMutation();
  return <ScreenContainer className="p-5" safeAreaClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={[styles.back, { color: colors.primary }]}>رجوع</Text></Pressable><Text style={[styles.eyebrow, { color: colors.primary }]}>مركز المساعدة</Text><Text style={[styles.title, { color: colors.foreground }]}>الشكاوى والدعم</Text><Text style={[styles.subtitle, { color: colors.muted }]}>احكِ لنا ما حدث وسيتابع فريق وصلني الحالة معك.</Text>{submitted ? <View style={[styles.success, { backgroundColor: "#E8F5EE" }]}><Text style={styles.successIcon}>✓</Text><Text style={[styles.successTitle, { color: colors.foreground }]}>تم تسجيل الشكوى</Text><Text style={[styles.meta, { color: colors.muted }]}>رقم الحالة {complaintId ? `WS-C-${complaintId}` : "قيد الإنشاء"} · سنعود إليك خلال ٢٤ ساعة.</Text><Pressable onPress={() => setSubmitted(false)} style={[styles.secondary, { borderColor: colors.border }]}><Text style={[styles.secondaryText, { color: colors.foreground }]}>تسجيل شكوى أخرى</Text></Pressable></View> : <><Text style={[styles.section, { color: colors.foreground }]}>نوع البلاغ</Text><View style={styles.categories}>{categories.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.category, { backgroundColor: category === item ? colors.primary : colors.surface, borderColor: category === item ? colors.primary : colors.border }]}><Text style={[styles.categoryText, { color: category === item ? "#FFFFFF" : colors.foreground }]}>{item}</Text></Pressable>)}</View><Text style={[styles.section, { color: colors.foreground }]}>تفاصيل الحالة</Text><TextInput multiline value={details} onChangeText={setDetails} placeholder="اكتب تفاصيل المشكلة أو الملاحظة..." placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.surface }]} /><Pressable onPress={async () => { if (!details.trim()) return; const result = await complaintMutation.mutateAsync({ category, description: details }); setComplaintId(result?.id ?? null); setSubmitted(true); setDetails(""); }} disabled={!details.trim() || complaintMutation.isPending} style={[styles.primary, { backgroundColor: colors.primary }, (!details.trim() || complaintMutation.isPending) && styles.disabled]}><Text style={styles.primaryText}>{complaintMutation.isPending ? "جارٍ الإرسال..." : "إرسال الشكوى"}</Text></Pressable></>}<View style={[styles.help, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.helpIcon}>☎️</Text><View style={styles.helpCopy}><Text style={[styles.helpTitle, { color: colors.foreground }]}>تحتاج مساعدة عاجلة؟</Text><Text style={[styles.meta, { color: colors.muted }]}>تواصل مع الدعم على مدار الساعة من داخل الرحلة.</Text></View></View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 32 }, back: { fontSize: 12, fontWeight: "800", textAlign: "right" }, eyebrow: { fontSize: 12, fontWeight: "800", textAlign: "right" }, title: { fontFamily: "Cairo_800ExtraBold", fontSize: 28, fontWeight: "800", textAlign: "right" }, subtitle: { fontSize: 13, lineHeight: 21, textAlign: "right" }, section: { fontFamily: "Cairo_700Bold", fontSize: 15, fontWeight: "800", textAlign: "right", marginTop: 5 }, categories: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, category: { borderWidth: 1, borderRadius: 13, paddingHorizontal: 12, paddingVertical: 10 }, categoryText: { fontSize: 11, fontWeight: "700" }, input: { minHeight: 130, borderWidth: 1, borderRadius: 16, padding: 13, textAlign: "right", textAlignVertical: "top", fontSize: 13 }, primary: { minHeight: 54, borderRadius: 16, justifyContent: "center", alignItems: "center" }, primaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, disabled: { opacity: 0.45 }, success: { borderRadius: 20, padding: 22, alignItems: "center", gap: 9 }, successIcon: { width: 52, height: 52, borderRadius: 26, backgroundColor: "#137A5A", color: "#FFFFFF", fontSize: 34, textAlign: "center", lineHeight: 50 }, successTitle: { fontFamily: "Cairo_700Bold", fontSize: 18, fontWeight: "800" }, meta: { fontSize: 10, lineHeight: 17, textAlign: "right" }, secondary: { minHeight: 48, borderWidth: 1, borderRadius: 14, paddingHorizontal: 15, justifyContent: "center", marginTop: 8 }, secondaryText: { fontSize: 12, fontWeight: "800" }, help: { borderWidth: 1, borderRadius: 17, padding: 14, flexDirection: "row-reverse", gap: 9, alignItems: "center" }, helpIcon: { fontSize: 22 }, helpCopy: { flex: 1, alignItems: "flex-end" }, helpTitle: { fontSize: 12, fontWeight: "800" } });
