import { desc, eq, gt, lt, and } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { adminSettings, auditLogs, driverDocuments, driverProfiles, familyComplaints, familyViolations, favoriteDrivers, InsertUser, notificationEvents, pushTokens, rideOffers, rideRatings, rides, users } from "../drizzle/schema";
import { ENV } from "./_core/env";
import { canSelectCarOffer, validateCarOfferInput } from "../shared/bidding";
import { storagePut } from "./storage";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) { console.warn("[Database] Cannot upsert user: database not available"); return; }
  const values: InsertUser = { openId: user.openId, name: user.name, email: user.email, phone: user.phone, loginMethod: user.loginMethod, role: user.role, appRole: user.appRole, lastSignedIn: user.lastSignedIn ?? new Date() };
  const updateSet: Record<string, unknown> = { lastSignedIn: values.lastSignedIn };
  for (const key of ["name", "email", "phone", "loginMethod", "role", "appRole"] as const) if (values[key] !== undefined) updateSet[key] = values[key];
  if (user.openId === ENV.ownerOpenId) { values.role = "admin"; values.appRole = "admin"; updateSet.role = "admin"; updateSet.appRole = "admin"; }
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet });
}
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function getUserById(id: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.id, id)).limit(1); return result[0]; }
export async function ensureDriverProfile(userId: number, vehicleType: "toktok" | "car" = "car") { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = await db.select().from(driverProfiles).where(eq(driverProfiles.userId, userId)).limit(1); if (existing[0]) return existing[0]; const result = await db.insert(driverProfiles).values({ userId, vehicleType }); const created = await db.select().from(driverProfiles).where(eq(driverProfiles.id, Number((result as any).insertId))).limit(1); return created[0]; }
export async function updateDriverAvailability(input: { userId: number; isOnline: boolean; lat?: number; lng?: number }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const profile = (await db.select().from(driverProfiles).where(eq(driverProfiles.userId, input.userId)).limit(1))[0]; if (!profile) throw new Error("ملف السائق غير موجود"); if (profile.accountStatus !== "active" || profile.subscriptionStatus !== "approved") throw new Error("السائق غير مؤهل للاتصال"); await db.update(driverProfiles).set({ isOnline: input.isOnline, lastLat: input.lat ?? profile.lastLat, lastLng: input.lng ?? profile.lastLng, lastLocationAt: input.isOnline ? new Date() : profile.lastLocationAt }).where(eq(driverProfiles.userId, input.userId)); return (await db.select().from(driverProfiles).where(eq(driverProfiles.userId, input.userId)).limit(1))[0]; }
export async function createRide(input: typeof rides.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database not available"); const result = await db.insert(rides).values(input); const created = await db.select().from(rides).where(eq(rides.id, Number((result as any).insertId))).limit(1); return created[0]; }
export async function getRideForUser(id: number, userId: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(rides).where(and(eq(rides.id, id), eq(rides.familyUserId, userId))).limit(1); return result[0]; }
export async function getRideById(id: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(rides).where(eq(rides.id, id)).limit(1); return result[0]; }
export async function listFamilyRides(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(rides).where(eq(rides.familyUserId, userId)).orderBy(desc(rides.requestedAt)); }
export async function listNearbyDrivers(lat: number, lng: number) { const db = await getDb(); if (!db) return []; const staleAfter = new Date(Date.now() - 15 * 60 * 1000); const result = await db.select().from(driverProfiles).where(and(eq(driverProfiles.isOnline, true), eq(driverProfiles.accountStatus, "active"), eq(driverProfiles.subscriptionStatus, "approved"), gt(driverProfiles.lastLat, lat - 0.2), lt(driverProfiles.lastLat, lat + 0.2), gt(driverProfiles.lastLng, lng - 0.2), lt(driverProfiles.lastLng, lng + 0.2), gt(driverProfiles.lastLocationAt, staleAfter))); return result; }
export async function addFavoriteDriver(familyUserId: number, driverUserId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); const driver = (await db.select().from(driverProfiles).where(and(eq(driverProfiles.userId, driverUserId), eq(driverProfiles.accountStatus, "active"))).limit(1))[0]; if (!driver) throw new Error("السائق غير متاح"); await db.insert(favoriteDrivers).values({ familyUserId, driverUserId }).onDuplicateKeyUpdate({ set: { driverUserId } }); return (await db.select().from(favoriteDrivers).where(and(eq(favoriteDrivers.familyUserId, familyUserId), eq(favoriteDrivers.driverUserId, driverUserId))).limit(1))[0]; }
export async function removeFavoriteDriver(familyUserId: number, driverUserId: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.delete(favoriteDrivers).where(and(eq(favoriteDrivers.familyUserId, familyUserId), eq(favoriteDrivers.driverUserId, driverUserId))); return { success: true }; }
export async function listFavoriteDrivers(familyUserId: number) { const db = await getDb(); if (!db) return []; return db.select({ favoriteId: favoriteDrivers.id, driverUserId: users.id, name: users.name, phone: users.phone, vehicleType: driverProfiles.vehicleType, accountStatus: driverProfiles.accountStatus, subscriptionStatus: driverProfiles.subscriptionStatus, isOnline: driverProfiles.isOnline, lastLat: driverProfiles.lastLat, lastLng: driverProfiles.lastLng }).from(favoriteDrivers).innerJoin(users, eq(users.id, favoriteDrivers.driverUserId)).innerJoin(driverProfiles, eq(driverProfiles.userId, favoriteDrivers.driverUserId)).where(eq(favoriteDrivers.familyUserId, familyUserId)); }
export async function listOpenCarRequests() { const db = await getDb(); if (!db) return []; return db.select().from(rides).where(and(eq(rides.vehicleType, "car"), eq(rides.status, "requested"))).orderBy(desc(rides.requestedAt)); }
export async function createCarOffer(input: { rideId: number; driverUserId: number; offeredPrice: number; etaMinutes: number }) { const db = await getDb(); if (!db) throw new Error("Database not available"); if (!validateCarOfferInput(input)) throw new Error("بيانات العرض غير صالحة"); const driver = (await db.select().from(driverProfiles).where(and(eq(driverProfiles.userId, input.driverUserId), eq(driverProfiles.vehicleType, "car"), eq(driverProfiles.accountStatus, "active"), eq(driverProfiles.subscriptionStatus, "approved"))).limit(1))[0]; if (!driver) throw new Error("السائق غير مؤهل لتقديم عرض"); const ride = (await db.select().from(rides).where(eq(rides.id, input.rideId)).limit(1))[0]; if (!ride || ride.vehicleType !== "car" || ride.status !== "requested") throw new Error("الرحلة غير متاحة للعروض"); const result = await db.insert(rideOffers).values(input); return (await db.select().from(rideOffers).where(eq(rideOffers.id, Number((result as any).insertId))).limit(1))[0]; }
export async function listRideOffers(rideId: number, familyUserId: number) {
  const db = await getDb();
  if (!db) return [];
  const ride = (await db.select().from(rides).where(and(eq(rides.id, rideId), eq(rides.familyUserId, familyUserId))).limit(1))[0];
  if (!ride) throw new Error("الرحلة غير موجودة");
  return db.select({
    id: rideOffers.id,
    rideId: rideOffers.rideId,
    driverUserId: rideOffers.driverUserId,
    offeredPrice: rideOffers.offeredPrice,
    etaMinutes: rideOffers.etaMinutes,
    status: rideOffers.status,
    driverName: users.name,
    vehicleNumber: driverProfiles.vehicleNumber,
    isOnline: driverProfiles.isOnline,
  }).from(rideOffers).innerJoin(users, eq(users.id, rideOffers.driverUserId)).innerJoin(driverProfiles, eq(driverProfiles.userId, rideOffers.driverUserId)).where(eq(rideOffers.rideId, rideId)).orderBy(desc(rideOffers.createdAt));
}
export async function selectCarOffer(input: { rideId: number; offerId: number; familyUserId: number }) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");
  const offer = (await db.select().from(rideOffers).where(and(eq(rideOffers.id, input.offerId), eq(rideOffers.rideId, input.rideId), eq(rideOffers.status, "pending"))).limit(1))[0];
  if (!offer) throw new Error("العرض غير متاح");
  const ride = (await db.select().from(rides).where(and(eq(rides.id, input.rideId), eq(rides.familyUserId, input.familyUserId))).limit(1))[0];
  if (!ride || !canSelectCarOffer({ rideStatus: ride.status, offerStatus: offer.status })) throw new Error("لا يمكن اختيار هذا العرض الآن");
  const rideUpdate = await db.update(rides).set({ driverUserId: offer.driverUserId, status: "accepted", acceptedAt: new Date() }).where(and(eq(rides.id, input.rideId), eq(rides.familyUserId, input.familyUserId), eq(rides.status, "requested")));
  if (Number((rideUpdate as any).affectedRows ?? 0) !== 1) throw new Error("تم اختيار سائق آخر أو لم تعد الرحلة متاحة");
  await db.update(rideOffers).set({ status: "rejected" }).where(eq(rideOffers.rideId, input.rideId));
  await db.update(rideOffers).set({ status: "selected" }).where(eq(rideOffers.id, input.offerId));
  return (await db.select().from(rideOffers).where(eq(rideOffers.id, input.offerId)).limit(1))[0];
}
export async function updateRideStatus(input: { id: number; status: "accepted" | "arriving" | "active" | "completed" | "cancelled"; actorUserId: number; actorRole: "family" | "driver" | "admin" }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = (await db.select().from(rides).where(eq(rides.id, input.id)).limit(1))[0]; if (!existing) throw new Error("الرحلة غير موجودة"); if (input.actorRole === "family" && existing.familyUserId !== input.actorUserId) throw new Error("لا يمكنك تعديل رحلة مستخدم آخر"); if (input.actorRole === "driver" && existing.driverUserId !== input.actorUserId) throw new Error("لا يمكنك تعديل رحلة غير مسندة إليك"); const transitions: Record<string, string[]> = { requested: ["accepted", "cancelled"], accepted: ["arriving", "cancelled"], arriving: ["active", "cancelled"], active: ["completed", "cancelled"], completed: [], cancelled: [] }; if (input.actorRole !== "admin" && !transitions[existing.status]?.includes(input.status)) throw new Error("انتقال حالة الرحلة غير مسموح"); const updatedDriverUserId = input.status === "accepted" && input.actorRole === "driver" ? input.actorUserId : existing.driverUserId; await db.update(rides).set({ status: input.status, driverUserId: updatedDriverUserId, acceptedAt: input.status === "accepted" ? new Date() : undefined, completedAt: input.status === "completed" ? new Date() : undefined }).where(eq(rides.id, input.id)); return (await db.select().from(rides).where(eq(rides.id, input.id)).limit(1))[0]; }
export async function createDriverDocument(input: { userId: number; documentType: string; fileName: string; mimeType: string; dataBase64: string }) { const db = await getDb(); if (!db) throw new Error("Database not available"); if (!input.dataBase64 || input.dataBase64.length > 15_000_000) throw new Error("ملف المستند غير صالح أو كبير جداً"); const uploaded = await storagePut(`drivers/${input.userId}/${input.documentType}/${input.fileName}`, Buffer.from(input.dataBase64, "base64"), input.mimeType); const result = await db.insert(driverDocuments).values({ userId: input.userId, documentType: input.documentType, fileName: input.fileName, mimeType: input.mimeType, storageKey: uploaded.key, storageUrl: uploaded.url }); return (await db.select().from(driverDocuments).where(eq(driverDocuments.id, Number((result as any).insertId))).limit(1))[0]; }
export async function listDriverDocuments(userId?: number) { const db = await getDb(); if (!db) return []; return userId ? db.select().from(driverDocuments).where(eq(driverDocuments.userId, userId)).orderBy(desc(driverDocuments.createdAt)) : db.select().from(driverDocuments).orderBy(desc(driverDocuments.createdAt)); }
export async function reviewDriverDocument(input: { documentId: number; status: "approved" | "rejected"; reviewReason: string; reviewedBy: number }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = (await db.select().from(driverDocuments).where(eq(driverDocuments.id, input.documentId)).limit(1))[0]; if (!existing) throw new Error("المستند غير موجود"); await db.update(driverDocuments).set({ status: input.status, reviewReason: input.reviewReason, reviewedBy: input.reviewedBy }).where(eq(driverDocuments.id, input.documentId)); await db.insert(auditLogs).values({ actorUserId: input.reviewedBy, action: `driver_document_${input.status}`, entityType: "driver_document", entityId: String(input.documentId), beforeValue: JSON.stringify({ status: existing.status, reviewReason: existing.reviewReason }), afterValue: JSON.stringify({ status: input.status, reviewReason: input.reviewReason }), metadata: JSON.stringify({ userId: existing.userId, documentType: existing.documentType }) }); return (await db.select().from(driverDocuments).where(eq(driverDocuments.id, input.documentId)).limit(1))[0]; }
export async function createRideRating(input: { rideId: number; familyUserId: number; rating: number; comment?: string | null }) { const db = await getDb(); if (!db) throw new Error("Database not available"); if (!Number.isInteger(input.rating) || input.rating < 1 || input.rating > 5) throw new Error("التقييم يجب أن يكون بين 1 و5"); const ride = (await db.select().from(rides).where(and(eq(rides.id, input.rideId), eq(rides.familyUserId, input.familyUserId))).limit(1))[0]; if (!ride || ride.status !== "completed" || !ride.driverUserId) throw new Error("لا يمكن تقييم هذا المشوار الآن"); const result = await db.insert(rideRatings).values({ rideId: input.rideId, familyUserId: input.familyUserId, driverUserId: ride.driverUserId, rating: input.rating, comment: input.comment ?? null }); return (await db.select().from(rideRatings).where(eq(rideRatings.id, Number((result as any).insertId))).limit(1))[0]; }
export async function listDriverRatings(driverUserId: number) { const db = await getDb(); if (!db) return []; return db.select().from(rideRatings).where(eq(rideRatings.driverUserId, driverUserId)).orderBy(desc(rideRatings.createdAt)); }
export async function recordNotificationEvent(input: { userId: number; eventKey: string; eventType: string; title: string; body: string; data?: Record<string, unknown> }) { const db = await getDb(); if (!db) return false; try { await db.insert(notificationEvents).values({ userId: input.userId, eventKey: input.eventKey, eventType: input.eventType, title: input.title, body: input.body, data: JSON.stringify(input.data ?? {}) }); return true; } catch (error) { if (String(error).toLowerCase().includes("duplicate")) return false; throw error; } }
export async function registerPushToken(input: typeof pushTokens.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(pushTokens).values(input).onDuplicateKeyUpdate({ set: { userId: input.userId, platform: input.platform, updatedAt: new Date() } }); }
export async function getPushTokens(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(pushTokens).where(eq(pushTokens.userId, userId)); }

export async function listAdminSettings() { const db = await getDb(); if (!db) return []; return db.select().from(adminSettings).orderBy(adminSettings.settingKey); }
export async function updateAdminSetting(input: { settingKey: string; settingValue: string; category: "pricing" | "permissions" | "subscription" | "notifications"; updatedBy: number }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = await db.select().from(adminSettings).where(eq(adminSettings.settingKey, input.settingKey)).limit(1); const beforeValue = existing[0]?.settingValue ?? null; if (existing[0]) await db.update(adminSettings).set({ settingValue: input.settingValue, category: input.category, updatedBy: input.updatedBy }).where(eq(adminSettings.settingKey, input.settingKey)); else await db.insert(adminSettings).values(input); await db.insert(auditLogs).values({ actorUserId: input.updatedBy, action: existing[0] ? "update" : "create", entityType: "admin_setting", entityId: input.settingKey, beforeValue, afterValue: input.settingValue, metadata: JSON.stringify({ category: input.category }) }); return (await db.select().from(adminSettings).where(eq(adminSettings.settingKey, input.settingKey)).limit(1))[0]; }
export async function listAdminAuditLogs(limit = 50) { const db = await getDb(); if (!db) return []; return db.select().from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(limit); }
export async function listNonDriverUsers() { const db = await getDb(); if (!db) return []; return db.select().from(users).where(eq(users.appRole, "family")).orderBy(desc(users.lastSignedIn)); }
export async function moderateNonDriverUser(input: { userId: number; status: "active" | "blocked" | "suspended_temp" | "suspended_permanent"; reason: string; suspendedUntil?: Date | null; moderatedBy: number }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = await db.select().from(users).where(eq(users.id, input.userId)).limit(1); const user = existing[0]; if (!user || user.appRole !== "family") throw new Error("Non-driver user not found"); await db.update(users).set({ userStatus: input.status, moderationReason: input.reason, suspendedUntil: input.suspendedUntil ?? null, moderatedBy: input.moderatedBy }).where(eq(users.id, input.userId)); if (input.status !== "active") await db.insert(familyViolations).values({ familyUserId: input.userId, category: input.status === "blocked" ? "حظر" : input.status === "suspended_temp" ? "إيقاف مؤقت" : "إيقاف دائم", reason: input.reason, source: "admin_moderation", createdBy: input.moderatedBy }); await db.insert(auditLogs).values({ actorUserId: input.moderatedBy, action: input.status, entityType: "family_user", entityId: String(input.userId), beforeValue: JSON.stringify({ userStatus: user.userStatus, moderationReason: user.moderationReason }), afterValue: JSON.stringify({ userStatus: input.status, moderationReason: input.reason, suspendedUntil: input.suspendedUntil ?? null }), metadata: JSON.stringify({ userName: user.name, userPhone: user.phone }) }); return (await db.select().from(users).where(eq(users.id, input.userId)).limit(1))[0]; }
export async function createFamilyComplaint(input: { familyUserId: number; category: string; title: string; description: string; relatedRideId?: number | null }) { const db = await getDb(); if (!db) throw new Error("Database not available"); if (input.relatedRideId) { const ride = await getRideForUser(input.relatedRideId, input.familyUserId); if (!ride) throw new Error("لا يمكن ربط الشكوى بمشوار غير تابع للحساب"); } const result = await db.insert(familyComplaints).values(input); return (await db.select().from(familyComplaints).where(eq(familyComplaints.id, Number((result as any).insertId))).limit(1))[0]; }
export async function updateFamilyComplaint(input: { complaintId: number; status: "open" | "in_review" | "resolved" | "closed"; adminNotes: string; updatedBy: number }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = await db.select().from(familyComplaints).where(eq(familyComplaints.id, input.complaintId)).limit(1); const complaint = existing[0]; if (!complaint) throw new Error("Complaint not found"); await db.update(familyComplaints).set({ status: input.status, adminNotes: input.adminNotes }).where(eq(familyComplaints.id, input.complaintId)); await db.insert(auditLogs).values({ actorUserId: input.updatedBy, action: "update", entityType: "family_complaint", entityId: String(input.complaintId), beforeValue: JSON.stringify({ status: complaint.status, adminNotes: complaint.adminNotes }), afterValue: JSON.stringify({ status: input.status, adminNotes: input.adminNotes }), metadata: JSON.stringify({ title: complaint.title, familyUserId: complaint.familyUserId }) }); return (await db.select().from(familyComplaints).where(eq(familyComplaints.id, input.complaintId)).limit(1))[0]; }
export async function getFamilyGovernanceHistory(userId: number) { const db = await getDb(); if (!db) return { violations: [], complaints: [], rides: [] }; const [violations, complaints, familyRides] = await Promise.all([db.select().from(familyViolations).where(eq(familyViolations.familyUserId, userId)).orderBy(desc(familyViolations.createdAt)), db.select().from(familyComplaints).where(eq(familyComplaints.familyUserId, userId)).orderBy(desc(familyComplaints.createdAt)), db.select().from(rides).where(eq(rides.familyUserId, userId)).orderBy(desc(rides.requestedAt))]); return { violations, complaints, rides: familyRides }; }
