import { desc, eq, gt, and } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { adminSettings, auditLogs, driverProfiles, familyComplaints, familyViolations, InsertUser, pushTokens, rides, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) { console.warn("[Database] Cannot upsert user: database not available"); return; }
  const values: InsertUser = { openId: user.openId, name: user.name, email: user.email, phone: user.phone, loginMethod: user.loginMethod, role: user.role, appRole: user.appRole, lastSignedIn: user.lastSignedIn ?? new Date() };
  const updateSet: Record<string, unknown> = { lastSignedIn: values.lastSignedIn };
  for (const key of ["name", "email", "phone", "loginMethod", "role", "appRole"] as const) if (values[key] !== undefined) updateSet[key] = values[key];
  if (user.openId === ENV.ownerOpenId) { values.role = "admin"; values.appRole = "admin"; updateSet.role = "admin"; updateSet.appRole = "admin"; }
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet });
}
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function getUserById(id: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.id, id)).limit(1); return result[0]; }
export async function ensureDriverProfile(userId: number, vehicleType: "toktok" | "car" = "car") { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = await db.select().from(driverProfiles).where(eq(driverProfiles.userId, userId)).limit(1); if (existing[0]) return existing[0]; const result = await db.insert(driverProfiles).values({ userId, vehicleType }); const created = await db.select().from(driverProfiles).where(eq(driverProfiles.id, Number((result as any).insertId))).limit(1); return created[0]; }
export async function createRide(input: typeof rides.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database not available"); const result = await db.insert(rides).values(input); const created = await db.select().from(rides).where(eq(rides.id, Number((result as any).insertId))).limit(1); return created[0]; }
export async function getRideForUser(id: number, userId: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(rides).where(and(eq(rides.id, id), eq(rides.familyUserId, userId))).limit(1); return result[0]; }
export async function listFamilyRides(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(rides).where(eq(rides.familyUserId, userId)).orderBy(desc(rides.requestedAt)); }
export async function listNearbyDrivers(lat: number, lng: number) { const db = await getDb(); if (!db) return []; const result = await db.select().from(driverProfiles).where(and(eq(driverProfiles.isOnline, true), eq(driverProfiles.accountStatus, "active"), eq(driverProfiles.subscriptionStatus, "approved"), gt(driverProfiles.lastLat, lat - 0.2), gt(driverProfiles.lastLng, lng - 0.2))); return result; }
export async function updateRideStatus(id: number, status: "accepted" | "arriving" | "active" | "completed" | "cancelled", driverUserId?: number) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.update(rides).set({ status, driverUserId, acceptedAt: status === "accepted" ? new Date() : undefined, completedAt: status === "completed" ? new Date() : undefined }).where(eq(rides.id, id)); }
export async function registerPushToken(input: typeof pushTokens.$inferInsert) { const db = await getDb(); if (!db) throw new Error("Database not available"); await db.insert(pushTokens).values(input).onDuplicateKeyUpdate({ set: { userId: input.userId, platform: input.platform, updatedAt: new Date() } }); }
export async function getPushTokens(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(pushTokens).where(eq(pushTokens.userId, userId)); }

export async function listAdminSettings() { const db = await getDb(); if (!db) return []; return db.select().from(adminSettings).orderBy(adminSettings.settingKey); }
export async function updateAdminSetting(input: { settingKey: string; settingValue: string; category: "pricing" | "permissions" | "subscription" | "notifications"; updatedBy: number }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = await db.select().from(adminSettings).where(eq(adminSettings.settingKey, input.settingKey)).limit(1); const beforeValue = existing[0]?.settingValue ?? null; if (existing[0]) await db.update(adminSettings).set({ settingValue: input.settingValue, category: input.category, updatedBy: input.updatedBy }).where(eq(adminSettings.settingKey, input.settingKey)); else await db.insert(adminSettings).values(input); await db.insert(auditLogs).values({ actorUserId: input.updatedBy, action: existing[0] ? "update" : "create", entityType: "admin_setting", entityId: input.settingKey, beforeValue, afterValue: input.settingValue, metadata: JSON.stringify({ category: input.category }) }); return (await db.select().from(adminSettings).where(eq(adminSettings.settingKey, input.settingKey)).limit(1))[0]; }
export async function listAdminAuditLogs(limit = 50) { const db = await getDb(); if (!db) return []; return db.select().from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(limit); }
export async function listNonDriverUsers() { const db = await getDb(); if (!db) return []; return db.select().from(users).where(eq(users.appRole, "family")).orderBy(desc(users.lastSignedIn)); }
export async function moderateNonDriverUser(input: { userId: number; status: "active" | "blocked" | "suspended_temp" | "suspended_permanent"; reason: string; suspendedUntil?: Date | null; moderatedBy: number }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const existing = await db.select().from(users).where(eq(users.id, input.userId)).limit(1); const user = existing[0]; if (!user || user.appRole !== "family") throw new Error("Non-driver user not found"); await db.update(users).set({ userStatus: input.status, moderationReason: input.reason, suspendedUntil: input.suspendedUntil ?? null, moderatedBy: input.moderatedBy }).where(eq(users.id, input.userId)); if (input.status !== "active") await db.insert(familyViolations).values({ familyUserId: input.userId, category: input.status === "blocked" ? "حظر" : input.status === "suspended_temp" ? "إيقاف مؤقت" : "إيقاف دائم", reason: input.reason, source: "admin_moderation", createdBy: input.moderatedBy }); await db.insert(auditLogs).values({ actorUserId: input.moderatedBy, action: input.status, entityType: "family_user", entityId: String(input.userId), beforeValue: JSON.stringify({ userStatus: user.userStatus, moderationReason: user.moderationReason }), afterValue: JSON.stringify({ userStatus: input.status, moderationReason: input.reason, suspendedUntil: input.suspendedUntil ?? null }), metadata: JSON.stringify({ userName: user.name, userPhone: user.phone }) }); return (await db.select().from(users).where(eq(users.id, input.userId)).limit(1))[0]; }
export async function createFamilyComplaint(input: { familyUserId: number; category: string; description: string; relatedRideId?: number | null }) { const db = await getDb(); if (!db) throw new Error("Database not available"); const result = await db.insert(familyComplaints).values(input); return (await db.select().from(familyComplaints).where(eq(familyComplaints.id, Number((result as any).insertId))).limit(1))[0]; }
export async function getFamilyGovernanceHistory(userId: number) { const db = await getDb(); if (!db) return { violations: [], complaints: [], rides: [] }; const [violations, complaints, familyRides] = await Promise.all([db.select().from(familyViolations).where(eq(familyViolations.familyUserId, userId)).orderBy(desc(familyViolations.createdAt)), db.select().from(familyComplaints).where(eq(familyComplaints.familyUserId, userId)).orderBy(desc(familyComplaints.createdAt)), db.select().from(rides).where(eq(rides.familyUserId, userId)).orderBy(desc(rides.requestedAt))]); return { violations, complaints, rides: familyRides }; }
