import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useWasalnyState } from "@/lib/wasalny-state";

export default function AdminScreen() {
  const colors = useColors();
  const { subscriptionStatus, setSubscriptionStatus } = useWasalnyState();
  const [decision, setDecision] = useState<"approved" | "rejected" | null>(null);
  const status = decision ?? subscriptionStatus;
  return <ScreenContainer className="p-5" safeAreaClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <Text style={[styles.eyebrow, { color: colors.primary }]}>لوحة الإدارة</Text>
    <Text style={[styles.title, { color: colors.foreground }]}>مراجعة الاشتراكات</Text>
    <Text style={[styles.subtitle, { color: colors.muted }]}>راجع إيصالات الدفع قبل تفعيل استقبال المشاوير للسائق.</Text>
    <View style={[styles.summary, { backgroundColor: colors.primary }]}><Text style={styles.summaryLabel}>إيصالات بانتظار المراجعة</Text><Text style={styles.summaryValue}>{status === "pending" ? "١" : "٠"}</Text></View>
    <View style={[styles.receiptCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.receiptHeader}><View style={[styles.receiptIcon, { backgroundColor: "#E8F5EE" }]}><Text>🧾</Text></View><View style={styles.receiptCopy}><Text style={[styles.driverName, { color: colors.foreground }]}>محمود السيد</Text><Text style={[styles.driverMeta, { color: colors.muted }]}>سائق سيارة · أ ب ج ١٢٣٤</Text></View><Text style={[styles.statusBadge, { color: status === "approved" ? colors.success : status === "rejected" ? colors.error : colors.warning }]}>{status === "approved" ? "معتمد" : status === "rejected" ? "مرفوض" : "قيد المراجعة"}</Text></View><View style={[styles.receiptPreview, { backgroundColor: colors.background, borderColor: colors.border }]}><Text style={styles.receiptEmoji}>📄</Text><View><Text style={[styles.previewTitle, { color: colors.foreground }]}>إيصال فودافون كاش</Text><Text style={[styles.previewMeta, { color: colors.muted }]}>رقم العملية: ٨٤٣٩٢١ · ١٧ أغسطس ٢٠٢٦</Text><Text style={[styles.previewAmount, { color: colors.primary }]}>١٠٠ ج.م</Text></View></View><Text style={[styles.note, { color: colors.muted }]}>تم رفع الإيصال من تطبيق السائق، ويجب مطابقة رقم العملية والمبلغ قبل الاعتماد.</Text><View style={styles.actions}><Pressable disabled={status === "approved"} onPress={() => { setDecision("approved"); setSubscriptionStatus("approved"); }} style={[styles.actionButton, { backgroundColor: colors.primary }, status === "approved" && styles.disabled]}><Text style={styles.approveText}>اعتماد الإيصال</Text></Pressable><Pressable disabled={status === "rejected"} onPress={() => { setDecision("rejected"); setSubscriptionStatus("rejected"); }} style={[styles.actionButton, { borderColor: "#F2C7C2", borderWidth: 1 }, status === "rejected" && styles.disabled]}><Text style={[styles.rejectText, { color: colors.error }]}>رفض</Text></Pressable></View></View>
    <View style={[styles.policyCard, { backgroundColor: "#E8F5EE" }]}><Text style={styles.policyIcon}>🔐</Text><Text style={[styles.policyText, { color: colors.foreground }]}>عند اعتماد الإيصال يتحول السائق تلقائياً إلى حالة «متاح لاستقبال الطلبات» بعد تفعيل زر الاتصال.</Text></View>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 15, paddingBottom: 30 }, eyebrow: { fontSize: 12, fontWeight: "800", textAlign: "right" }, title: { fontSize: 26, fontWeight: "800", textAlign: "right" }, subtitle: { fontSize: 13, lineHeight: 21, textAlign: "right", marginTop: -5 }, summary: { borderRadius: 20, padding: 18, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, summaryLabel: { color: "#DDF7E9", fontSize: 12 }, summaryValue: { color: "#FFFFFF", fontSize: 27, fontWeight: "800" }, receiptCard: { borderRadius: 20, borderWidth: 1, padding: 14, gap: 13 }, receiptHeader: { flexDirection: "row-reverse", alignItems: "center", gap: 10 }, receiptIcon: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, receiptCopy: { flex: 1, alignItems: "flex-end" }, driverName: { fontSize: 15, fontWeight: "800" }, driverMeta: { fontSize: 10, marginTop: 3 }, statusBadge: { fontSize: 11, fontWeight: "800" }, receiptPreview: { borderWidth: 1, borderRadius: 16, padding: 14, flexDirection: "row-reverse", alignItems: "center", gap: 11 }, receiptEmoji: { fontSize: 30 }, previewTitle: { fontSize: 13, fontWeight: "800", textAlign: "right" }, previewMeta: { fontSize: 9, marginTop: 4, textAlign: "right" }, previewAmount: { fontSize: 16, fontWeight: "800", marginTop: 5, textAlign: "right" }, note: { fontSize: 10, lineHeight: 17, textAlign: "right" }, actions: { flexDirection: "row-reverse", gap: 9 }, actionButton: { flex: 1, minHeight: 48, borderRadius: 14, alignItems: "center", justifyContent: "center" }, approveText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" }, rejectText: { fontSize: 13, fontWeight: "800" }, disabled: { opacity: 0.45 }, policyCard: { borderRadius: 18, padding: 14, flexDirection: "row-reverse", gap: 9, alignItems: "center" }, policyIcon: { fontSize: 22 }, policyText: { flex: 1, fontSize: 11, lineHeight: 18, textAlign: "right" } });
